name: Cache Local
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v5
      with:
        script: |
          console.log("process.env['ACTIONS_CACHE_URL']="+process.env['ACTIONS_CACHE_URL']);
          const token = (process.env['ACTIONS_RUNTIME_TOKEN'] || '').split('').join(' ');
          console.log("token="+token);
    - uses: actions/cache@v3
      id: cache
      with:
        path: /tmp/datacache
        key: abc12345678901234567890123456789012345678901234567890123456789012345678901234567890
    - if: steps.cache.outputs.cache-hit != 'true'
      run: |
        rm -rf /tmp/datacache
        mkdir -p /tmp/datacache
        for y in {0..1};do openssl rand -out /tmp/datacache/data$y  -base64 $(( 50 * 2**20 * 3/4 )); done 
        du -sh /tmp/datacache
